version: '3.5'

services:

  stream-app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: stream-app
    networks:
      - wiki-stream-network

networks:
  wiki-stream-network:
    external: true