version: '3.5'
services :
  db:
    image: postgres:14-alpine
    container_name: db_wiki
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: wiki
      POSTGRES_PASSWORD: q1w2e3r4t5
      POSTGRES_DB: wikimedia
    networks:
      - wiki-stream-network

  admin:
    image: adminer
    container_name: db_admin
    depends_on:
      - db
    ports:
      - 8080:8080
    networks:
      - wiki-stream-network


networks:
  wiki-stream-network:
    external: true